set(ALGOFORGE_TOOLCHAIN_MSVC 1 CACHE BOOL "Build with Microsoft MSVC" FORCE)
set(ALGOFORGE_TOOLCHAIN_CLANG 0 CACHE BOOL "Build with LLVM clang-cl" FORCE)
set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} /DALGOFORGE_TOOLCHAIN_MSVC=1")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} /DALGOFORGE_TOOLCHAIN_MSVC=1")
