if(NOT DEFINED OUTPUT_FILE OR OUTPUT_FILE STREQUAL "")
  message(FATAL_ERROR "OUTPUT_FILE is required")
endif()
if(NOT DEFINED PLUGIN_MODULE OR PLUGIN_MODULE STREQUAL "")
  message(FATAL_ERROR "PLUGIN_MODULE is required")
endif()

get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${OUTPUT_FILE}" "format=1\n")
file(APPEND "${OUTPUT_FILE}" "plugin=${PLUGIN_MODULE}\n")
foreach(runtime_file IN LISTS RUNTIME_FILES)
  if(NOT runtime_file STREQUAL "" AND NOT runtime_file STREQUAL PLUGIN_MODULE)
    file(APPEND "${OUTPUT_FILE}" "runtime=${runtime_file}\n")
  endif()
endforeach()
